name: Deploy with SAM

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'main.py'
      - 'config.py'
      - 'requirements.txt'
      - 'template.yaml'

jobs:
  deploy-sam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      
      - name: Build SAM application
        run: sam build --use-container
      
      - name: Deploy SAM application
        run: sam deploy --stack-name classcharts-calendar-prod --no-confirm-changeset --no-fail-on-empty-changeset --parameter-overrides Environment="prod" BucketName="classcharts-cal" CalendarFilename="ical.ics" SecretName="classcharts/credentials" --resolve-s3